# Generated by Django 4.0 on 2021-12-25 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("venues", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tag_events", to="events.EventTag"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_events",
                to="auth.user",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="venue_events",
                to="venues.venue",
            ),
        ),
        migrations.AlterField(
            model_name="eventseat",
            name="event_seat_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_seats",
                to="events.eventseattype",
            ),
        ),
        migrations.AlterField(
            model_name="eventseattype",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_seat_types",
                to="events.event",
            ),
        ),
    ]
