# Generated by Django 4.0 on 2022-01-04 12:45

import django.contrib.postgres.functions
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_tags_alter_event_user_alter_event_venue_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('start_date__gt', django.contrib.postgres.functions.TransactionNow()), ('start_date__lt', django.db.models.expressions.F('end_date'))), name='events_event_start_date_is_lt_end_date_and_now'),
        ),
    ]
