# Generated by Django 4.0 on 2021-12-21 08:27

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="ticket_number",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
