# Generated by Django 4.0 on 2021-12-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_alter_reservation_ticket_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.SmallIntegerField(
                choices=[(1, "Created"), (2, "Invalidated"), (4, "Reserved")], default=1
            ),
        ),
    ]
