# Generated by Django 4.0 on 2021-12-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_removed_cancelled_reservation_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"default_related_name": "reservations"},
        ),
        migrations.RemoveConstraint(
            model_name="reservationeventseat",
            name="unique_reservation_event_seat",
        ),
        migrations.AddConstraint(
            model_name="reservationeventseat",
            constraint=models.UniqueConstraint(
                fields=("reservation", "event_seat"),
                name="reservations_reservationeventseat_unique_reservation_event_seat",
            ),
        ),
    ]
